name: CI

on:
  push:
    branches: master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout project
        uses: actions/checkout@v2.6.0
        
      - name: Setup JAVA 11  
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 11
      
      - name: Assemble Debug Build
        run: ./gradlew assembleDebug

  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.6.0
      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 11
          
      - name: Run Unit Test
        run: ./gradlew app:test
      

