name: Publish build to play store

on:
  workflow_dispatch:
    inputs:
      inputs:
        track:
          description: Select track
          required: true
          default: 'production'
          type: choice
          options:
            - production
            - beta
            - alpha
            - internalsharing
            - internal

        userFraction:
          description: Enter user fraction 0.0-1.0
          required: true
          type: string

        whatsNew:
          description: Enter What's New
          type: string



jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.6.0

      - uses: ./.github/actions/setup

      - name: Build aab
        env:
          SIGNING_KEY_STORE_PATH: ${{ secrets.SIGNING_KEY_STORE_PATH }}
          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
          SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
        run: ./gradlew bundleRelease

      - name: Publish on Play Store internal track
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          packageName: com.aman.showtv
          releaseFiles: app/build/outputs/bundle/release/app-release.aab
          track: ${{inputs.track}}
          userFraction: ${{inputs.userFraction}}
          whatsNewDirectory: ${{inputs.whatsNew}}
          mappingFile: app/build/outputs/mapping/release/mapping.txt
          debugSymbols: app/intermediates/merged_native_libs/release/out/lib
