name: Release build

on:
  pull_request:
  push:
    branches: master
    tags:
     - v*

jobs:
  release_build:
   runs-on: ubuntu-latest

   steps:
     - uses: actions/checkout@v2.6.0
     - uses: actions/setup-java@v3
       with:
         distribution: 'corretto'
         java-version: 11

     - name: Decode Keystore
       env:
            ENCODED_STRING: ${{ secrets.SIGNING_KEY_STORE_BASE64 }}
            SIGNING_KEY_STORE_PATH: ${{ secrets.SIGNING_KEY_STORE_PATH }}

       run: |
            echo $ENCODED_STRING > keystore-b64.txt
            base64 -d -i keystore-b64.txt -o $SIGNING_KEY_STORE_PATH


     - name: Build Release apk
       env:
         SIGNING_KEY_STORE_PATH: ${{ secrets.SIGNING_KEY_STORE_PATH }}
         SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
         SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
         SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
       run: ./gradlew assembleRelease

     - name: Upload Release Build to Artifacts
       uses: actions/upload-artifact@v3
       with:
         name: release-artifacts
         path: app/release

